security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        from_database:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            lazy: true
            provider: app_user_provider
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            
            #http_basic: true

            form_login: 
                check_path: login

            logout:
                path: /logout
                target: /
            

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

    encoders:
        App\Entity\User: 
            algorithm: bcrypt
            cost: 12
        